namespace CatalogApplication.Seed.SeedData;

internal static class ProductXmlSeedData
{
    internal static readonly Dictionary<string, Dictionary<string, string[]>> ProductSpecsByCategoryNew = new() {
        // Computers & Laptops
        {
            CategorySeedData.PrimaryCategories[0], new Dictionary<string, string[]> {
                { "Processor Type", ["Intel Core i9", "Intel Core i7", "Intel Core i5", "Intel Core i3", "AMD Ryzen 9", "AMD Ryzen 7", "AMD Ryzen 5", "Apple M1", "Qualcomm Snapdragon", "Other"] },
                { "RAM Capacity", ["2GB", "4GB", "8GB", "16GB", "32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "2TB", "More than 2TB"] },
                { "Storage Capacity", ["128GB", "256GB", "512GB", "1TB", "2TB", "4TB", "8TB", "More than 8TB"] },
                { "Screen Size", ["11 inches", "13 inches", "15 inches", "17 inches", "20 inches", "More than 20 inches"] },
                { "Resolution", ["HD (720p)", "Full HD (1080p)", "Quad HD (1440p)", "4K Ultra HD (2160p)", "5K", "8K", "Other"] },
                { "Graphics Card", ["NVIDIA GeForce RTX", "NVIDIA GeForce GTX", "AMD Radeon RX", "Intel Iris Xe", "Integrated Graphics", "Other"] },
                { "Operating System", ["Windows 10", "Windows 11", "macOS", "iOS", "iPadOS", "Android", "Chrome OS", "Linux", "Other"] },
                { "Battery Life", ["Up to 4 hours", "4-8 hours", "8-12 hours", "12-16 hours", "16+ hours"] },
                { "Weight", ["Less than 1 kg", "1-2 kg", "2-3 kg", "3-4 kg", "4+ kg"] },
                { "Dimensions", ["Compact", "Standard", "Large"] },
                { "Ports", ["USB Type-A", "USB Type-C", "HDMI", "Thunderbolt", "Ethernet", "Audio Jack", "SD Card Slot", "Other"] },
                { "Touchscreen", ["Yes", "No"] },
                { "Keyboard Type", ["Mechanical", "Membrane", "Scissor", "Other"] },
                { "Mouse Type", ["Wired", "Wireless", "Bluetooth", "Gaming", "Other"] },
                { "Webcam Resolution", ["720p", "1080p", "4K", "Other"] },
                { "Refresh Rate", ["60Hz", "75Hz", "120Hz", "144Hz", "240Hz", "Other"] },
                { "Connectivity", ["Wi-Fi", "Bluetooth", "Ethernet", "NFC", "5G", "4G LTE", "Other"] },
                { "Brand", ["Apple", "Dell", "HP", "Lenovo", "Asus", "Acer", "Microsoft", "Samsung", "Sony", "LG", "Other"] },
                { "Color", ["Black", "White", "Silver", "Gray", "Blue", "Red", "Green", "Gold", "Rose Gold", "Other"] },
                { "Material", ["Aluminum", "Plastic", "Carbon Fiber", "Glass", "Stainless Steel", "Other"] },
                { "Warranty Period", ["1 year", "2 years", "3 years", "5 years", "Lifetime"] },
                { "Price", ["Under $500", "$500 - $1000", "$1000 - $1500", "$1500 - $2000", "Over $2000"] },
                { "Laptop Type", ["Ultrabook", "Gaming Laptop", "2-in-1 Convertible", "Chromebook", "Workstation", "Other"] },
                { "Touchpad Type", ["Precision Touchpad", "Standard Touchpad", "Button-less Touchpad", "Other"] },
                { "Convertible", ["Yes", "No"] },
                { "Fingerprint Scanner", ["Yes", "No"] },
                { "Form Factor", ["ATX", "Micro-ATX", "Mini-ITX", "Extended ATX", "Other"] },
                { "CPU Cooling", ["Air Cooling", "Liquid Cooling", "Other"] },
                { "Power Supply", ["ATX", "SFX", "TFX", "Other"] },
                { "Expansion Slots", ["PCIe x16", "PCIe x8", "PCIe x4", "PCIe x1", "Other"] },
                { "Display Technology", ["LCD", "LED", "OLED", "QLED", "IPS", "TN", "VA", "Other"] },
                { "Storage Type", ["HDD", "SSD", "NVMe SSD", "Hybrid Drive", "Other"] },
                { "Battery Capacity", ["3000mAh", "4000mAh", "5000mAh", "6000mAh", "7000mAh", "8000mAh", "Other"] },
                { "Stylus Support", ["Yes", "No"] },
                { "Panel Type", ["IPS", "TN", "VA", "OLED", "Other"] },
                { "Response Time", ["1ms", "2ms", "4ms", "5ms", "Other"] },
                { "Aspect Ratio", ["16:9", "16:10", "21:9", "4:3", "Other"] },
                { "Curved", ["Yes", "No"] },
                { "Compatibility", ["Windows", "macOS", "Linux", "Android", "iOS", "Other"] },
                { "Interface", ["USB", "Thunderbolt", "PCIe", "SATA", "Other"] },
                { "Cable Length", ["1 foot", "3 feet", "6 feet", "10 feet", "15 feet", "Other"] },
                { "Processor Speed", ["2 GHz", "3 GHz", "4 GHz", "5 GHz", "Other"] },
                { "VR Ready", ["Yes", "No"] },
                { "Overclocking Support", ["Yes", "No"] },
                { "Console Type", ["PlayStation", "Xbox", "Nintendo Switch", "Other"] },
                { "Controller Type", ["Standard Controller", "Wireless Controller", "Gaming Mouse and Keyboard", "Other"] },
                { "Genre", ["Action", "Adventure", "RPG", "FPS", "Sports", "Strategy", "Simulation", "Other"] },
                { "Platform", ["PC", "PlayStation", "Xbox", "Nintendo Switch", "Mobile", "Other"] },
                { "ESRB Rating", ["Everyone (E)", "Everyone 10+ (E10+)", "Teen (T)", "Mature (M)", "Adults Only (AO)", "Rating Pending (RP)"] },
                { "Multiplayer Support", ["Local", "Online", "LAN", "Split-Screen", "Other"] },
                { "Peripheral Type", ["Keyboard", "Mouse", "Gamepad", "Joystick", "Headset", "Other"] },
                { "Wireless Technology", ["Bluetooth", "Wi-Fi", "RF", "Other"] }
            }
        },
        // Smartphones & Tablets
        {
            CategorySeedData.PrimaryCategories[1], new Dictionary<string, string[]> {
                { "Processor Type", ["Snapdragon 888", "Snapdragon 870", "Exynos 2100", "Apple A14 Bionic", "Apple A15 Bionic", "Kirin 9000", "Other"] },
                { "RAM Capacity", ["2GB", "4GB", "6GB", "8GB", "12GB", "16GB", "More than 16GB"] },
                { "Storage Capacity", ["32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "More than 1TB"] },
                { "Screen Size", ["Less than 5 inches", "5-6 inches", "6-7 inches", "7-8 inches", "8+ inches"] },
                { "Resolution", ["HD (720p)", "Full HD (1080p)", "Quad HD (1440p)", "4K Ultra HD (2160p)", "Other"] },
                { "Camera Resolution", ["8MP", "12MP", "16MP", "20MP", "24MP", "32MP", "More than 32MP"] },
                { "Battery Capacity", ["1000mAh", "2000mAh", "3000mAh", "4000mAh", "5000mAh", "6000mAh", "More than 6000mAh"] },
                { "Operating System", ["Android", "iOS", "iPadOS", "Other"] },
                { "Weight", ["Less than 100g", "100-200g", "200-300g", "300-400g", "400g+"] },
                { "Dimensions", ["Compact", "Standard", "Large"] },
                { "Connectivity", ["5G", "4G LTE", "Wi-Fi", "Bluetooth", "NFC", "Other"] },
                { "Color", ["Black", "White", "Silver", "Gold", "Blue", "Red", "Green", "Other"] },
                { "Material", ["Plastic", "Glass", "Metal", "Ceramic", "Other"] },
                { "Water Resistance", ["IP67", "IP68", "Splash resistant", "Waterproof", "No"] },
                { "Wireless Charging", ["Yes", "No"] },
                { "Fast Charging", ["Yes", "No"] },
                { "Biometric Authentication", ["Face Unlock", "Fingerprint Scanner", "Other"] },
                { "Face Unlock", ["Yes", "No"] },
                { "Fingerprint Scanner", ["In-display", "Rear-mounted", "Side-mounted", "No"] },
                { "Sensors", ["Accelerometer", "Gyroscope", "Proximity", "Compass", "Barometer", "Heart Rate", "Other"] },
                { "SIM Type", ["Nano-SIM", "Micro-SIM", "eSIM", "Dual SIM", "Single SIM"] },
                { "Expandable Storage", ["MicroSD", "Nano Memory (NM)", "Other", "None"] },
                { "Display Technology", ["AMOLED", "LCD", "IPS LCD", "OLED", "Other"] },
                { "Touchscreen Type", ["Capacitive", "Resistive", "Other"] },
                { "Stylus Support", ["Yes", "No"] },
                { "Smartwatch OS", ["WatchOS", "Wear OS", "Tizen OS", "Other"] },
                { "Heart Rate Monitor", ["Yes", "No"] },
                { "Sleep Tracking", ["Yes", "No"] },
                { "Fitness Tracking", ["Yes", "No"] },
                { "Mobile Accessory Type", ["Case", "Screen Protector", "Charger", "Cable", "Mount", "Other"] },
                { "Compatibility", ["iOS", "Android", "Universal", "Other"] },
                { "Charging Port", ["USB Type-C", "Lightning", "Micro USB", "Other"] },
                { "Cable Length", ["1 foot", "3 feet", "6 feet", "10 feet", "Other"] },
                { "Mounting Type", ["Handheld", "Armband", "Car mount", "Bike mount", "Other"] },
                { "Protective Features", ["Shockproof", "Dust-proof", "Drop-resistant", "Scratch-resistant", "Other"] }
            }
        },
        // TVs & Home Entertainment
        {
            CategorySeedData.PrimaryCategories[2], new Dictionary<string, string[]> {
                { "Screen Size", ["32 inches", "40 inches", "50 inches", "55 inches", "65 inches", "75 inches", "85 inches", "More than 85 inches"] },
                { "Resolution", ["HD (720p)", "Full HD (1080p)", "4K Ultra HD (2160p)", "8K Ultra HD (4320p)", "Other"] },
                { "Display Technology", ["LED", "OLED", "QLED", "NanoCell", "LCD", "Other"] },
                { "HDR Support", ["HDR10", "Dolby Vision", "HLG", "HDR10+", "Other"] },
                { "Refresh Rate", ["60Hz", "120Hz", "240Hz", "Variable Refresh Rate (VRR)", "Other"] },
                { "Smart TV Features", ["Smart Hub", "Voice Control", "Streaming Apps", "Screen Mirroring", "Other"] },
                { "Audio Output", ["Stereo", "Dolby Audio", "DTS", "Other"] },
                { "Speaker Configuration", ["2.0 Channel", "2.1 Channel", "5.1 Channel", "7.1 Channel", "Other"] },
                { "Sound Technology", ["Dolby Atmos", "DTS:X", "Virtual Surround", "Other"] },
                { "Connectivity", ["Wi-Fi", "Ethernet", "Bluetooth", "HDMI", "USB", "Other"] },
                { "HDMI Ports", ["1", "2", "3", "4", "More than 4"] },
                { "USB Ports", ["1", "2", "3", "4", "More than 4"] },
                { "Streaming Services", ["Netflix", "Amazon Prime Video", "Disney+", "Hulu", "YouTube", "Other"] },
                { "Media Compatibility", ["AVI", "MP4", "MKV", "MP3", "AAC", "Other"] },
                { "Projection Technology", ["DLP", "LCD", "LCoS", "Other"] },
                { "Brightness", ["300 nits", "500 nits", "1000 nits", "2000 nits", "Other"] },
                { "Contrast Ratio", ["1000:1", "2000:1", "5000:1", "10000:1", "Other"] },
                { "Throw Ratio", ["Short Throw", "Normal Throw", "Long Throw", "Other"] },
                { "Keystone Correction", ["Manual", "Automatic", "None"] },
                { "Lamp Life", ["5000 hours", "10000 hours", "20000 hours", "50000 hours", "Other"] },
                { "Aspect Ratio", ["16:9", "16:10", "4:3", "21:9", "Other"] },
                { "Home Theater System Type", ["Soundbar", "Component System", "Home Theater in a Box (HTIB)", "Other"] },
                { "Number of Speakers", ["2", "3", "5", "7", "More than 7"] },
                { "Power Output", ["100W", "200W", "500W", "1000W", "Other"] },
                { "Surround Sound Formats", ["Dolby Digital", "DTS", "THX", "Other"] },
                { "Media Player Type", ["Streaming Stick", "Set-Top Box", "Blu-ray Player", "DVD Player", "Other"] },
                { "Supported Formats", ["AVI", "MP4", "MKV", "MP3", "AAC", "Other"] },
                { "Storage Capacity", ["8GB", "16GB", "32GB", "64GB", "128GB", "Other"] },
                { "Remote Control Type", ["Infrared (IR)", "RF (Radio Frequency)", "Bluetooth", "Other"] },
                { "Mounting Options", ["Tabletop Stand", "Wall Mount", "Ceiling Mount", "Other"] },
                { "Cable Length", ["1 meter", "2 meters", "3 meters", "5 meters", "Other"] },
                { "Compatibility", ["HDMI", "USB", "Bluetooth", "Wi-Fi", "Other"] }
            }
        },
        // Cameras & Photography
        {
            CategorySeedData.PrimaryCategories[3], new Dictionary<string, string[]> {
                { "Megapixels", ["10MP", "20MP", "24MP", "30MP", "40MP", "50MP", "More than 50MP"] },
                { "Sensor Type", ["CMOS", "CCD", "BIS", "Other"] },
                { "Lens Mount", ["Canon EF", "Nikon F", "Sony E", "Micro Four Thirds", "Other"] },
                { "Lens Type", ["Prime", "Zoom", "Wide Angle", "Macro", "Telephoto", "Other"] },
                { "Aperture Range", ["f/1.8", "f/2.8", "f/4", "f/5.6", "Other"] },
                { "Focal Length", ["24mm", "35mm", "50mm", "85mm", "100mm", "200mm", "More than 200mm"] },
                { "Image Stabilization", ["Yes", "No"] },
                { "Autofocus System", ["Phase Detection", "Contrast Detection", "Hybrid", "Other"] },
                { "ISO Range", ["ISO 100", "ISO 200", "ISO 400", "ISO 800", "ISO 1600", "Other"] },
                { "Shutter Speed", ["1/1000 sec", "1/2000 sec", "1/4000 sec", "1/8000 sec", "Other"] },
                { "Viewfinder Type", ["Optical", "Electronic", "None"] },
                { "LCD Screen Size", ["2 inches", "3 inches", "3.2 inches", "3.5 inches", "Other"] },
                { "Video Resolution", ["HD (720p)", "Full HD (1080p)", "4K Ultra HD (2160p)", "Other"] },
                { "Frame Rate", ["24fps", "30fps", "60fps", "120fps", "Other"] },
                { "Recording Formats", ["JPEG", "RAW", "MP4", "AVCHD", "Other"] },
                { "Wireless Connectivity", ["Wi-Fi", "Bluetooth", "NFC", "Other"] },
                { "Waterproof", ["Yes", "No"] },
                { "Shockproof", ["Yes", "No"] },
                { "Freezeproof", ["Yes", "No"] },
                { "Action Camera Type", ["Helmet Mount", "Body Mount", "360-degree", "Other"] },
                { "Drone Type", ["Quadcopter", "Hexacopter", "Octocopter", "Other"] },
                { "Flight Time", ["10 minutes", "20 minutes", "30 minutes", "40 minutes", "Other"] },
                { "Maximum Range", ["100 meters", "500 meters", "1 kilometer", "5 kilometers", "Other"] },
                { "Camera Drone Resolution", ["1080p", "4K", "6K", "Other"] },
                { "Gimbal Stabilization", ["2-axis", "3-axis", "4-axis", "Other"] },
                { "Battery Capacity", ["1000mAh", "2000mAh", "3000mAh", "4000mAh", "Other"] },
                { "Compatible Devices", ["iOS Devices", "Android Devices", "Windows PCs", "Mac Computers", "Other"] },
                { "Storage Type", ["SD Card", "microSD Card", "CFexpress", "Internal Memory", "Other"] },
                { "Tripod Mount", ["1/4 inch", "3/8 inch", "Other"] },
                { "Camera Bag Type", ["Backpack", "Shoulder Bag", "Sling Bag", "Hard Case", "Other"] },
                { "Filter Size", ["52mm", "58mm", "67mm", "77mm", "Other"] },
                { "Compatibility", ["Windows", "macOS", "iOS", "Android", "Other"] }
            }
        },
        // Audio & Headphones
        {
            CategorySeedData.PrimaryCategories[4], new Dictionary<string, string[]> {
                { "Driver Type", ["Dynamic", "Planar Magnetic", "Electrostatic", "Other"] },
                { "Sound Quality", ["Hi-Res Audio", "Studio Quality", "Enhanced Bass", "Balanced Sound", "Other"] },
                { "Frequency Response", ["20Hz - 20kHz", "10Hz - 40kHz", "Other"] },
                { "Impedance", ["16 ohms", "32 ohms", "64 ohms", "150 ohms", "Other"] },
                { "Sensitivity", ["90 dB", "100 dB", "110 dB", "120 dB", "Other"] },
                { "Noise Cancellation", ["Active Noise Cancellation (ANC)", "Passive Noise Cancellation", "No Noise Cancellation"] },
                { "Microphone Type", ["Built-in", "Detachable Boom", "In-Line", "Other"] },
                { "Wireless Technology", ["Bluetooth", "RF", "Infrared (IR)", "Other"] },
                { "Bluetooth Version", ["Bluetooth 4.2", "Bluetooth 5.0", "Bluetooth 5.1", "Bluetooth 5.2", "Other"] },
                { "Battery Life", ["Up to 10 hours", "10-20 hours", "20-30 hours", "30+ hours"] },
                { "Fit Type", ["In-Ear", "On-Ear", "Over-Ear", "Neckband", "Other"] },
                { "Earbud Type", ["True Wireless Earbuds", "Wireless Earbuds with Neckband", "Wired Earbuds", "Other"] },
                { "Headband Type", ["Adjustable", "Fixed", "Other"] },
                { "Speaker Configuration", ["Mono", "Stereo", "2.1 Channel", "5.1 Channel", "Other"] },
                { "Power Output", ["10W", "20W", "50W", "100W", "Other"] },
                { "Frequency Range", ["FM (88MHz - 108MHz)", "AM (530kHz - 1710kHz)", "Other"] },
                { "Connectivity", ["Bluetooth", "Wi-Fi", "Auxiliary (AUX)", "USB", "Other"] },
                { "Audio Input", ["3.5mm Audio Jack", "USB", "Bluetooth", "Other"] },
                { "Supported Audio Formats", ["MP3", "AAC", "WAV", "FLAC", "Other"] },
                { "Playback Controls", ["Buttons", "Touch Controls", "Voice Control", "Other"] },
                { "Water Resistance", ["IPX4", "IPX5", "IPX7", "IPX8", "Other"] },
                { "Portability", ["Portable", "Desktop", "Other"] },
                { "Smart Assistant Integration", ["Amazon Alexa", "Google Assistant", "Apple Siri", "Other"] },
                { "Equalizer", ["Customizable Equalizer", "Pre-set Equalizer Modes", "No Equalizer"] },
                { "Home Audio System Type", ["Soundbar", "Bookshelf Speakers", "Floorstanding Speakers", "Home Theater System", "Other"] },
                { "Channels", ["2.0 Channel", "2.1 Channel", "5.1 Channel", "7.1 Channel", "Other"] },
                { "Total Power Output", ["50W", "100W", "200W", "500W", "Other"] },
                { "MP3 Player Type", ["Portable MP3 Player", "MP3 Player with Bluetooth", "Other"] },
                { "Storage Capacity", ["8GB", "16GB", "32GB", "64GB", "Other"] },
                { "Screen Size", ["1.8 inches", "2.4 inches", "3 inches", "Other"] },
                { "Audio Accessory Type", ["Headphone Case", "Earbud Tips", "Audio Cable", "Other"] },
                { "Compatibility", ["Windows", "macOS", "iOS", "Android", "Other"] },
                { "Cable Length", ["1 meter", "2 meters", "3 meters", "5 meters", "Other"] },
                { "Mounting Options", ["Wall Mount", "Desktop Stand", "Ceiling Mount", "Other"] }
            }
        },
        // Wearable Technology
        {
            CategorySeedData.PrimaryCategories[5], new Dictionary<string, string[]> {
                { "Display Type", ["OLED", "AMOLED", "LCD", "E-Ink", "Other"] },
                { "Display Size", ["1 inch", "1.2 inches", "1.4 inches", "1.6 inches", "Other"] },
                { "Resolution", ["320x320", "360x360", "454x454", "512x512", "Other"] },
                { "Touchscreen", ["Yes", "No"] },
                { "Fitness Tracking", ["Steps", "Distance", "Calories Burned", "Active Minutes", "Other"] },
                { "Heart Rate Monitor", ["Optical Heart Rate Sensor", "ECG", "PPG", "Other"] },
                { "GPS", ["GPS", "GLONASS", "Galileo", "Beidou", "Other"] },
                { "Water Resistance", ["IPX7", "IPX8", "50 meters water resistance", "Other"] },
                { "Battery Life", ["Up to 1 day", "1-2 days", "2-3 days", "3-5 days", "5+ days"] },
                { "Operating System", ["Wear OS", "watchOS", "Fitbit OS", "Tizen", "Other"] },
                { "Compatibility", ["iOS", "Android", "iOS & Android", "Other"] },
                { "Strap Material", ["Silicone", "Leather", "Metal", "Nylon", "Other"] },
                { "Sensors", ["Accelerometer", "Gyroscope", "Ambient Light Sensor", "Barometer", "Other"] },
                { "Activity Recognition", ["Walking", "Running", "Cycling", "Swimming", "Other"] },
                { "Sleep Tracking", ["Sleep Duration", "Sleep Stages", "Sleep Score", "Other"] },
                { "Sports Modes", ["Running", "Cycling", "Swimming", "Yoga", "Other"] },
                { "Smartwatch OS", ["Wear OS", "watchOS", "Fitbit OS", "Tizen", "Other"] },
                { "Fitness Tracker Type", ["Smartwatch", "Fitness Band", "Smart Ring", "Other"] },
                { "Step Counting", ["Yes", "No"] },
                { "Calorie Tracking", ["Yes", "No"] },
                { "Sleep Monitoring", ["Yes", "No"] },
                { "Movement Reminders", ["Yes", "No"] },
                { "VR Headset Type", ["Standalone", "PCVR", "Mobile VR", "Other"] },
                { "Field of View", ["90 degrees", "100 degrees", "110 degrees", "120 degrees", "Other"] },
                { "Refresh Rate", ["60Hz", "72Hz", "90Hz", "120Hz", "Other"] },
                { "Tracking Sensors", ["Accelerometer", "Gyroscope", "Magnetometer", "Other"] },
                { "Controller Type", ["Handheld Controller", "Hand Tracking", "Other"] },
                { "Wearable Accessory Type", ["Charging Cable", "Replacement Straps", "Screen Protectors", "Other"] },
                { "Compatibility", ["iOS", "Android", "iOS & Android", "Other"] },
                { "Adjustability", ["Adjustable Strap", "Buckle Closure", "Hook-and-loop Closure", "Other"] },
                { "Charging Type", ["USB Type-C", "Proprietary Charger", "Wireless Charging", "Other"] }
            }
        },
        // Cables & Adapters
        {
            CategorySeedData.PrimaryCategories[6], new Dictionary<string, string[]> {
                { "Connector Type", ["USB Type-A", "USB Type-C", "Micro USB", "Lightning", "HDMI", "DVI", "VGA", "Ethernet", "Other"] },
                { "Cable Length", ["1 foot", "3 feet", "6 feet", "10 feet", "15 feet", "Other"] },
                { "Data Transfer Speed", ["USB 2.0 (480 Mbps)", "USB 3.0 (5 Gbps)", "USB 3.1 (10 Gbps)", "USB 3.2 (20 Gbps)", "Other"] },
                { "Charging Speed", ["Standard Charging", "Fast Charging", "Quick Charging", "Other"] },
                { "Compatibility", ["PC", "Mac", "Android", "iOS", "Other"] },
                { "Durability", ["Standard", "Braided", "Reinforced", "Other"] },
                { "Shielding", ["Unshielded", "Shielded", "Other"] },
                { "Connector Material", ["Gold-plated", "Nickel-plated", "Aluminum", "Other"] },
                { "Color", ["Black", "White", "Gray", "Blue", "Red", "Other"] },
                { "Cable Type", ["Charging Cable", "Data Cable", "Audio Cable", "Video Cable", "Other"] },
                { "USB Standard", ["USB 2.0", "USB 3.0", "USB 3.1", "USB 3.2", "Other"] },
                { "Lightning Connector Type", ["Lightning to USB-A", "Lightning to USB-C", "Other"] },
                { "HDMI Version", ["HDMI 1.4", "HDMI 2.0", "HDMI 2.1", "Other"] },
                { "Resolution Support", ["1080p", "4K", "8K", "Other"] },
                { "DVI Version", ["DVI-D", "DVI-I", "DVI-A", "Other"] },
                { "Charger Type", ["Wall Charger", "Car Charger", "Wireless Charger", "Other"] },
                { "Power Output", ["5W", "10W", "18W", "20W", "Other"] },
                { "Number of Ports", ["1 Port", "2 Ports", "4 Ports", "Other"] },
                { "Fast Charging Support", ["QC 2.0", "QC 3.0", "QC 4.0", "PD", "Other"] },
                { "Power Bank Capacity", ["5000mAh", "10000mAh", "20000mAh", "Other"] },
                { "Battery Type", ["Li-ion", "Li-polymer", "Other"] },
                { "Voltage", ["5V", "9V", "12V", "Other"] },
                { "Capacity", ["mAh", "mAh", "mAh", "Other"] },
                { "Recharge Cycles", ["500 cycles", "1000 cycles", "2000 cycles", "Other"] },
                { "Chemistry", ["NiMH", "NiCd", "Lead Acid", "Other"] },
                { "Size", ["AAA", "AA", "C", "D", "Other"] }
            }
        },
        // Storage Devices
        {
            CategorySeedData.PrimaryCategories[7], new Dictionary<string, string[]> {
                { "Capacity", ["128GB", "256GB", "512GB", "1TB", "2TB", "4TB", "8TB", "Other"] },
                { "Interface", ["SATA III", "NVMe PCIe", "USB 3.0", "USB 3.1", "USB-C", "Thunderbolt", "Other"] },
                { "Read Speed", ["Up to 500 MB/s", "Up to 1000 MB/s", "Up to 2000 MB/s", "Other"] },
                { "Write Speed", ["Up to 300 MB/s", "Up to 500 MB/s", "Up to 1000 MB/s", "Other"] },
                { "Form Factor", ["2.5 inches", "M.2 2280", "M.2 2242", "mSATA", "PCIe Card", "Other"] },
                { "Compatibility", ["PC", "Mac", "Linux", "Android", "Other"] },
                { "Encryption", ["AES 128-bit", "AES 256-bit", "Hardware Encryption", "Software Encryption", "Other"] },
                { "Shock Resistance", ["Up to 1000G", "Up to 1500G", "Up to 2000G", "Other"] },
                { "Water Resistance", ["IPX4", "IPX7", "IPX8", "Other"] },
                { "USB Standard", ["USB 2.0", "USB 3.0", "USB 3.1", "USB 3.2", "Other"] },
                { "Connector Type", ["USB Type-A", "USB Type-C", "Micro USB", "Other"] },
                { "Cache Size", ["8MB", "16MB", "32MB", "64MB", "Other"] },
                { "Rotation Speed", ["5400 RPM", "7200 RPM", "10000 RPM", "Other"] },
                { "Storage Technology", ["HDD", "SSD", "Hybrid Drive", "Other"] },
                { "NAND Type", ["SLC", "MLC", "TLC", "QLC", "Other"] },
                { "Controller", ["Phison", "Samsung", "Silicon Motion", "Other"] },
                { "Trim Support", ["Yes", "No"] },
                { "Power Consumption", ["Idle: 1W", "Active: 5W", "Other"] },
                { "Operating Temperature", ["0°C to 70°C", "-20°C to 85°C", "Other"] },
                { "Dimensions", ["2.5\" Drive: 7mm", "2.5\" Drive: 9.5mm", "M.2 2280: 22mm x 80mm", "Other"] },
                { "Weight", ["50g", "100g", "150g", "200g", "Other"] }
            }
        },
        // Home Appliances
        {
            CategorySeedData.PrimaryCategories[8], new Dictionary<string, string[]> {
                { "Capacity", ["5 kg", "7 kg", "10 kg", "12 kg", "15 kg", "Other"] },
                { "Load Type", ["Top Load", "Front Load", "Other"] },
                { "Washing Programs", ["Normal", "Quick Wash", "Delicate", "Heavy Duty", "Steam Clean", "Other"] },
                { "Spin Speed", ["600 RPM", "800 RPM", "1000 RPM", "1200 RPM", "1400 RPM", "Other"] },
                { "Energy Efficiency", ["Energy Star Rated", "A+++", "A++", "A+", "A", "Other"] },
                { "Water Consumption", ["Low", "Medium", "High", "Other"] },
                { "Noise Level", ["Low", "Medium", "High", "Other"] },
                { "Dryer Type", ["Vented", "Condenser", "Heat Pump", "Other"] },
                { "Drying Capacity", ["5 kg", "7 kg", "10 kg", "Other"] },
                { "Drying Programs", ["Cotton", "Synthetics", "Delicates", "Quick Dry", "Other"] },
                { "Vacuum Type", ["Upright", "Canister", "Stick", "Robot", "Other"] },
                { "Suction Power", ["Low", "Medium", "High", "Other"] },
                { "Dust Capacity", ["0.5 L", "1 L", "2 L", "3 L", "Other"] },
                { "Filter Type", ["HEPA", "Cyclonic", "Foam", "Other"] },
                { "Carpet Cleaner Type", ["Upright", "Portable", "Carpet Washer", "Other"] },
                { "Cleaning Width", ["25 cm", "30 cm", "35 cm", "40 cm", "Other"] },
                { "Water Tank Capacity", ["1 L", "2 L", "3 L", "Other"] },
                { "Microwave Capacity", ["20 liters", "25 liters", "30 liters", "Other"] },
                { "Power Output", ["600W", "800W", "1000W", "1200W", "Other"] },
                { "Cooking Modes", ["Microwave", "Grill", "Convection", "Combination", "Other"] },
                { "Oven Capacity", ["30 liters", "40 liters", "50 liters", "Other"] },
                { "Number of Racks", ["1 Rack", "2 Racks", "3 Racks", "Other"] },
                { "Refrigerator Capacity", ["100 liters", "200 liters", "300 liters", "Other"] },
                { "Defrost Type", ["Manual", "Frost-Free", "Other"] },
                { "Freezer Capacity", ["50 liters", "100 liters", "150 liters", "Other"] },
                { "Cooling Technology", ["Compressor", "Inverter", "Dual Cooling", "Other"] },
                { "Dishwasher Type", ["Built-in", "Freestanding", "Compact", "Other"] },
                { "Place Settings", ["6 Place Settings", "8 Place Settings", "12 Place Settings", "Other"] },
                { "Wash Programs", ["Normal", "Quick Wash", "Heavy", "Eco", "Other"] },
                { "Color", ["White", "Black", "Stainless Steel", "Silver", "Other"] },
                { "Material", ["Stainless Steel", "Plastic", "Glass", "Other"] },
                { "Dimensions", ["Compact", "Standard", "Large", "Other"] },
                { "Weight", ["10 kg", "20 kg", "30 kg", "40 kg", "Other"] }
            }
        },
        // Office Electronics
        {
            CategorySeedData.PrimaryCategories[9], new Dictionary<string, string[]> {
                { "Printer Type", ["Inkjet", "Laser", "LED", "Dot Matrix", "Other"] },
                { "Printing Technology", ["Monochrome", "Color", "Other"] },
                { "Print Speed", ["Up to 20 ppm", "Up to 30 ppm", "Up to 50 ppm", "Other"] },
                { "Print Resolution", ["600 dpi", "1200 dpi", "2400 dpi", "Other"] },
                { "Scanner Type", ["Flatbed", "Sheetfed", "Document Camera", "Other"] },
                { "Scan Resolution", ["600 dpi", "1200 dpi", "2400 dpi", "Other"] },
                { "Document Feeder", ["Automatic Document Feeder (ADF)", "Manual", "Other"] },
                { "Duplex Printing", ["Yes", "No"] },
                { "Connectivity", ["USB", "Ethernet", "Wi-Fi", "Bluetooth", "Other"] },
                { "Projector Type", ["LCD", "DLP", "LED", "Laser", "Other"] },
                { "Projection Technology", ["Standard (4:3)", "Widescreen (16:9)", "Other"] },
                { "Brightness", ["Up to 2000 lumens", "2000 - 3000 lumens", "3000 - 4000 lumens", "Other"] },
                { "Resolution", ["SVGA (800x600)", "XGA (1024x768)", "Full HD (1920x1080)", "4K (3840x2160)", "Other"] },
                { "Throw Ratio", ["Short Throw", "Standard Throw", "Long Throw", "Other"] },
                { "Keystone Correction", ["Manual", "Automatic", "None"] },
                { "Office Accessory Type", ["Desk Organizer", "Monitor Stand", "Keyboard Tray", "Other"] },
                { "Compatibility", ["PC", "Mac", "Linux", "Other"] },
                { "Color", ["Black", "White", "Gray", "Other"] },
                { "Material", ["Plastic", "Metal", "Wood", "Other"] },
                { "Dimensions", ["Compact", "Standard", "Large", "Other"] },
                { "Calculator Type", ["Basic", "Scientific", "Graphing", "Printing", "Other"] },
                { "Power Source", ["Battery", "Solar", "Electric", "Other"] },
                { "Functions", ["Basic Arithmetic", "Graphing", "Financial", "Other"] },
                { "Display Type", ["LCD", "LED", "Dot Matrix", "Other"] },
                { "Shredder Type", ["Strip-Cut", "Cross-Cut", "Micro-Cut", "Other"] },
                { "Sheet Capacity", ["Up to 10 sheets", "Up to 20 sheets", "Up to 50 sheets", "Other"] },
                { "Shred Size", ["P-1", "P-2", "P-3", "P-4", "Other"] },
                { "Run Time", ["Continuous", "5 minutes", "10 minutes", "Other"] },
                { "Security Level", ["Level P-2", "Level P-3", "Level P-4", "Other"] }
            }
        }
    };
}